import type { Metadata } from "next";
import NavBar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja-JP">
            <body className="flex flex-col h-screen">
                <NavBar />
                <main className="flex-1 basis-0 flex flex-col overflow-auto">
                    {children}
                </main>
            </body>
        </html>
    );
}
